export const DESKTOP_TOP_BAR_HEIGHT_PX = 46;
export const MAC_TRAFFIC_LIGHT_INSET_X_PX = 16;
export const MAC_TRAFFIC_LIGHT_DOT_RADIUS_PX = 7;
export const MAC_SIDEBAR_LEADING_INSET_PX = 90;
export const SIDEBAR_TOGGLE_BUTTON_SIZE_PX = 28;
export const SIDEBAR_TOGGLE_CONTENT_GAP_PX = 4;

export const COLLAPSED_CHAT_CONTENT_INSET_PX =
	MAC_SIDEBAR_LEADING_INSET_PX + SIDEBAR_TOGGLE_BUTTON_SIZE_PX + SIDEBAR_TOGGLE_CONTENT_GAP_PX;

export function getMacTrafficLightPosition(): { x: number; y: number } {
	return {
		x: MAC_TRAFFIC_LIGHT_INSET_X_PX,
		y: Math.round(DESKTOP_TOP_BAR_HEIGHT_PX / 2 - MAC_TRAFFIC_LIGHT_DOT_RADIUS_PX),
	};
}
